# The name of the H2 database :
spring.datasource.url=jdbc:h2:mem:testdb
# automatic creation and modification of tables
spring.jpa.hibernate.ddl-auto=update
# Activate the H2 console :
spring.h2.console.enabled=true
# For customizing the console URL
spring.h2.console.path=/h2
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
springdoc.api-docs.path=/docs
#For customising the swagger path
springdoc.swagger-ui.path=/test
#for sorting by using the name of the method
springdoc.swagger-ui.operationsSorter=method